version: '3.5'
services:
  mysql:
    image: mariadb:10.4
    command:
      - --default-authentication-plugin=mysql_native_password
      - --character-set-server=utf8
      - --collation-server=utf8_general_ci
      - --innodb-buffer-pool-size=1G
    volumes:
      - ./db:/var/lib/mysql/
      - ./logs:/var/log/mysql/
    ports:
      # host:container
      - 3306:3306
    network_mode: bridge
#    networks:
#      default:
#        aliases:
#            - dbalias
    environment:
      - MYSQL_ROOT_PASSWORD=mysql
    container_name: mysqldb
    #restart: always

#networks:
#  default:
#    name: magenet
#    external: true