version: '3.5'
services:
  nginx:
    image: nginx:1.22.0
    volumes:
      - ./nginx:/etc/nginx/conf.d/
      - ./logs:/var/log/nginx/
    ports:
      - 80:80
    network_mode: bridge
    container_name: nginx
    #restart: always

#networks:
#  default:
#    name: magenet
#    external: true