nginx:
  image: wolfsellers/nginx:1.8
  volumes:
    - ./nginx:/etc/nginx/conf.d/
    - ../services_logs/nginx:/var/log/nginx/
  ports:
    - 80:80
    - 443:443
  container_name: nginx
  restart: always

